import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Terms of Service | RankBoast",
    description: "Read RankBoast's Terms of Service — the rules that govern your use of the platform.",
};

const LAST_UPDATED = "10 March 2026";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground">
            <div className="max-w-3xl mx-auto px-6 py-16">

                <div className="mb-10">
                    <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-2">Terms of Service</h1>
                    <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
                </div>

                <div className="space-y-8 text-muted-foreground leading-relaxed text-sm sm:text-base">

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">1. Acceptance of Terms</h2>
                        <p>By accessing or using RankBoast AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">2. Use of the Service</h2>
                        <p>You agree to use RankBoast only for lawful purposes. You must not:</p>
                        <ul className="list-disc pl-5 space-y-1 mt-2">
                            <li>Attempt to scan, audit, or scrape websites without authorisation from the site owner.</li>
                            <li>Use the Service to generate spam, malicious content, or misleading SEO data.</li>
                            <li>Reverse-engineer, resell, or redistribute the Service without written permission.</li>
                            <li>Abuse the AI models to generate illegal, hateful, or harmful content.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">3. Accounts</h2>
                        <p>You are responsible for maintaining the security of your account credentials. You must notify us immediately if you suspect unauthorised access. We reserve the right to suspend accounts that violate these terms.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">4. Intellectual Property</h2>
                        <p>The RankBoast platform, its UI, and underlying algorithms are our intellectual property. SEO reports and AI-generated content produced using our Service are owned by you, subject to these Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">5. Free Plan and Paid Plans</h2>
                        <p>We offer a free tier with usage limits. Paid plans are billed monthly and can be cancelled at any time. Refunds are issued only in cases of technical failure on our part. We reserve the right to change pricing with 30 days&apos; notice.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">6. Disclaimer of Warranties</h2>
                        <p>The Service is provided &quot;as is&quot; without warranties of any kind. SEO scores and recommendations are generated by AI and should be independently verified. We do not guarantee specific search ranking improvements.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">7. Limitation of Liability</h2>
                        <p>To the maximum extent permitted by law, RankBoast AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">8. Termination</h2>
                        <p>We may terminate or suspend your account at any time for violations of these Terms. You may also delete your account at any time through your profile settings.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">9. Changes to Terms</h2>
                        <p>We reserve the right to update these Terms. Continued use of the Service after changes constitutes acceptance of the new Terms. We will notify registered users of material changes by email.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">10. Governing Law</h2>
                        <p>These Terms are governed by applicable law. Any disputes shall be resolved through good-faith negotiation first, or arbitration if needed.</p>
                    </section>

                    <section>
                        <h2 className="text-foreground font-bold text-lg mb-2">11. Contact</h2>
                        <p>Questions about these Terms? <Link href="/contact" className="text-indigo-400 hover:underline">Contact us</Link>.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
